---
#  ________________________________
# < Dev machine configuration file >
#  --------------------------------
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#
# Change settings here to control your dev environment.
ansible:
  version: 1.6.3
vagrant:
  version: 1.6.2
virtualbox:
  version: 4.3.12-93733

# Vagrant box definition
# Ubuntu
#  box: 'ubuntu/trusty64'
# Centos
  box: 'hansode/centos-6.5-x86_64'

# Webserver settings
  webserver_hostname: 'dev.local'
  webserver_hostname_alias: 'www.{{ webserver_hostname }}'

# Vagrantfile configuration
  boxipaddress: "192.168.110.110"
  boxname: "dev"
  host_synced_folder: "./docroot"

# Install components:
# - To install a component set it to "y".
# - To leave a component out of the install set the value to "n".
  java_install: "y"
  tomcat_install: "y"

# HTTP port for the web server.
  http_port: 80

# Administration email (used in instances when a server email is needed)
  admin_mail: 'steve@stevepereira.ca'

# Set the level of verbosity that Ansible will use
# This can be one of "", "v", "vv", "vvv", or "vvvv"
  ansible_verbosity: "v"
