VAGRANTFILE_API_VERSION = "2"

# Ubuntu
#box='ubuntu/trusty64'
# Centos
box='hansode/centos-6.5-x86_64'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = box
  config.vm.network :private_network, ip: "192.168.33.33"

  # Manage vbguest update
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  # Ansible Provision
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
    ansible.verbose = "vvvv"
    #ansible.raw_arguments = ['-v']
  end

end
